// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>This is typed as an enum for consistency with `requirements.disabled_reason`, but it safe to assume `future_requirements.disabled_reason` is null because fields in `future_requirements` will never disable the account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Account_capability_future_requirements_disabled_reason
    {
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "paused.inactivity")]
        #pragma warning disable CS1591
        PausedInactivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending.onboarding")]
        #pragma warning disable CS1591
        PendingOnboarding,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending.review")]
        #pragma warning disable CS1591
        PendingReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "platform_disabled")]
        #pragma warning disable CS1591
        Platform_disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "platform_paused")]
        #pragma warning disable CS1591
        Platform_paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected.inactivity")]
        #pragma warning disable CS1591
        RejectedInactivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected.other")]
        #pragma warning disable CS1591
        RejectedOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected.unsupported_business")]
        #pragma warning disable CS1591
        RejectedUnsupported_business,
        #pragma warning restore CS1591
        [EnumMember(Value = "requirements.fields_needed")]
        #pragma warning disable CS1591
        RequirementsFields_needed,
        #pragma warning restore CS1591
    }
}
