// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>The code for the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountRequirementsErrorCode
    {
        [EnumMember(Value = "external_request")]
        #pragma warning disable CS1591
        ExternalRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "information_missing")]
        #pragma warning disable CS1591
        InformationMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_address_city_state_postal_code")]
        #pragma warning disable CS1591
        InvalidAddressCityStatePostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_address_highway_contract_box")]
        #pragma warning disable CS1591
        InvalidAddressHighwayContractBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_address_private_mailbox")]
        #pragma warning disable CS1591
        InvalidAddressPrivateMailbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_business_profile_name")]
        #pragma warning disable CS1591
        InvalidBusinessProfileName,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_business_profile_name_denylisted")]
        #pragma warning disable CS1591
        InvalidBusinessProfileNameDenylisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_company_name_denylisted")]
        #pragma warning disable CS1591
        InvalidCompanyNameDenylisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_dob_age_over_maximum")]
        #pragma warning disable CS1591
        InvalidDobAgeOverMaximum,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_dob_age_under_18")]
        #pragma warning disable CS1591
        InvalidDobAgeUnder18,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_dob_age_under_minimum")]
        #pragma warning disable CS1591
        InvalidDobAgeUnderMinimum,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_product_description_length")]
        #pragma warning disable CS1591
        InvalidProductDescriptionLength,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_product_description_url_match")]
        #pragma warning disable CS1591
        InvalidProductDescriptionUrlMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_representative_country")]
        #pragma warning disable CS1591
        InvalidRepresentativeCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_signator")]
        #pragma warning disable CS1591
        InvalidSignator,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_statement_descriptor_business_mismatch")]
        #pragma warning disable CS1591
        InvalidStatementDescriptorBusinessMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_statement_descriptor_denylisted")]
        #pragma warning disable CS1591
        InvalidStatementDescriptorDenylisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_statement_descriptor_length")]
        #pragma warning disable CS1591
        InvalidStatementDescriptorLength,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_statement_descriptor_prefix_denylisted")]
        #pragma warning disable CS1591
        InvalidStatementDescriptorPrefixDenylisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_statement_descriptor_prefix_mismatch")]
        #pragma warning disable CS1591
        InvalidStatementDescriptorPrefixMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_street_address")]
        #pragma warning disable CS1591
        InvalidStreetAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_tax_id")]
        #pragma warning disable CS1591
        InvalidTaxId,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_tax_id_format")]
        #pragma warning disable CS1591
        InvalidTaxIdFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_tos_acceptance")]
        #pragma warning disable CS1591
        InvalidTosAcceptance,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_denylisted")]
        #pragma warning disable CS1591
        InvalidUrlDenylisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_format")]
        #pragma warning disable CS1591
        InvalidUrlFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_web_presence_detected")]
        #pragma warning disable CS1591
        InvalidUrlWebPresenceDetected,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_business_information_mismatch")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteBusinessInformationMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_empty")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_inaccessible")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteInaccessible,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_inaccessible_geoblocked")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteInaccessibleGeoblocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_inaccessible_password_protected")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteInaccessiblePasswordProtected,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_cancellation_policy")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteCancellationPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_customer_service_details")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteCustomerServiceDetails,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_legal_restrictions")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteLegalRestrictions,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_refund_policy")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteRefundPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_return_policy")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteReturnPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_terms_and_conditions")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteTermsAndConditions,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_incomplete_under_construction")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteIncompleteUnderConstruction,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_url_website_other")]
        #pragma warning disable CS1591
        InvalidUrlWebsiteOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_value_other")]
        #pragma warning disable CS1591
        InvalidValueOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported_business_type")]
        #pragma warning disable CS1591
        UnsupportedBusinessType,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_directors_mismatch")]
        #pragma warning disable CS1591
        VerificationDirectorsMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_address_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentAddressMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_address_missing")]
        #pragma warning disable CS1591
        VerificationDocumentAddressMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_corrupt")]
        #pragma warning disable CS1591
        VerificationDocumentCorrupt,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_country_not_supported")]
        #pragma warning disable CS1591
        VerificationDocumentCountryNotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_directors_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentDirectorsMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_dob_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentDobMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_duplicate_type")]
        #pragma warning disable CS1591
        VerificationDocumentDuplicateType,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_expired")]
        #pragma warning disable CS1591
        VerificationDocumentExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_failed_copy")]
        #pragma warning disable CS1591
        VerificationDocumentFailedCopy,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_failed_greyscale")]
        #pragma warning disable CS1591
        VerificationDocumentFailedGreyscale,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_failed_other")]
        #pragma warning disable CS1591
        VerificationDocumentFailedOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_failed_test_mode")]
        #pragma warning disable CS1591
        VerificationDocumentFailedTestMode,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_fraudulent")]
        #pragma warning disable CS1591
        VerificationDocumentFraudulent,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_id_number_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentIdNumberMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_id_number_missing")]
        #pragma warning disable CS1591
        VerificationDocumentIdNumberMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_incomplete")]
        #pragma warning disable CS1591
        VerificationDocumentIncomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_invalid")]
        #pragma warning disable CS1591
        VerificationDocumentInvalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_issue_or_expiry_date_missing")]
        #pragma warning disable CS1591
        VerificationDocumentIssueOrExpiryDateMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_manipulated")]
        #pragma warning disable CS1591
        VerificationDocumentManipulated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_missing_back")]
        #pragma warning disable CS1591
        VerificationDocumentMissingBack,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_missing_front")]
        #pragma warning disable CS1591
        VerificationDocumentMissingFront,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_name_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentNameMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_name_missing")]
        #pragma warning disable CS1591
        VerificationDocumentNameMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_nationality_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentNationalityMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_not_readable")]
        #pragma warning disable CS1591
        VerificationDocumentNotReadable,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_not_signed")]
        #pragma warning disable CS1591
        VerificationDocumentNotSigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_not_uploaded")]
        #pragma warning disable CS1591
        VerificationDocumentNotUploaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_photo_mismatch")]
        #pragma warning disable CS1591
        VerificationDocumentPhotoMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_too_large")]
        #pragma warning disable CS1591
        VerificationDocumentTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_document_type_not_supported")]
        #pragma warning disable CS1591
        VerificationDocumentTypeNotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_extraneous_directors")]
        #pragma warning disable CS1591
        VerificationExtraneousDirectors,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_address_match")]
        #pragma warning disable CS1591
        VerificationFailedAddressMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_authorizer_authority")]
        #pragma warning disable CS1591
        VerificationFailedAuthorizerAuthority,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_business_iec_number")]
        #pragma warning disable CS1591
        VerificationFailedBusinessIecNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_document_match")]
        #pragma warning disable CS1591
        VerificationFailedDocumentMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_id_number_match")]
        #pragma warning disable CS1591
        VerificationFailedIdNumberMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_keyed_identity")]
        #pragma warning disable CS1591
        VerificationFailedKeyedIdentity,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_keyed_match")]
        #pragma warning disable CS1591
        VerificationFailedKeyedMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_name_match")]
        #pragma warning disable CS1591
        VerificationFailedNameMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_other")]
        #pragma warning disable CS1591
        VerificationFailedOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_representative_authority")]
        #pragma warning disable CS1591
        VerificationFailedRepresentativeAuthority,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_residential_address")]
        #pragma warning disable CS1591
        VerificationFailedResidentialAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_tax_id_match")]
        #pragma warning disable CS1591
        VerificationFailedTaxIdMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_failed_tax_id_not_issued")]
        #pragma warning disable CS1591
        VerificationFailedTaxIdNotIssued,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_legal_entity_structure_mismatch")]
        #pragma warning disable CS1591
        VerificationLegalEntityStructureMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_missing_directors")]
        #pragma warning disable CS1591
        VerificationMissingDirectors,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_missing_executives")]
        #pragma warning disable CS1591
        VerificationMissingExecutives,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_missing_owners")]
        #pragma warning disable CS1591
        VerificationMissingOwners,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_rejected_ownership_exemption_reason")]
        #pragma warning disable CS1591
        VerificationRejectedOwnershipExemptionReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_requires_additional_memorandum_of_associations")]
        #pragma warning disable CS1591
        VerificationRequiresAdditionalMemorandumOfAssociations,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_requires_additional_proof_of_registration")]
        #pragma warning disable CS1591
        VerificationRequiresAdditionalProofOfRegistration,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_supportability")]
        #pragma warning disable CS1591
        VerificationSupportability,
        #pragma warning restore CS1591
    }
}
