// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount"/>, <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Discount"/>, <see cref="global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItemBranch1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoiceDiscountsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount? DeletedDiscount { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount DeletedDiscount { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Discount"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.Discount? Discount { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.Discount Discount { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItemBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItemBranch1? InvoiceDiscountsItemBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItemBranch1 InvoiceDiscountsItemBranch1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItem();
            result.DeletedDiscount = new global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount();
            result.Discount = new global::Soenneker.Stripe.OpenApiClient.Models.Discount();
            result.InvoiceDiscountsItemBranch1 = new global::Soenneker.Stripe.OpenApiClient.Models.InvoiceDiscountsItemBranch1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DeletedDiscount != null || Discount != null || InvoiceDiscountsItemBranch1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(DeletedDiscount, Discount, InvoiceDiscountsItemBranch1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.DeletedDiscount>(null, DeletedDiscount, Discount, InvoiceDiscountsItemBranch1);
        }
    }
}
#pragma warning restore CS0618
