// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>The effective display preference value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Payment_method_config_resource_display_preference_value
    {
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "on")]
        #pragma warning disable CS1591
        On,
        #pragma warning restore CS1591
    }
}
