// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentPagesCheckoutSessionCustomText : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Custom text that should be displayed after the payment confirmation button.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextAfterSubmit? AfterSubmit { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextAfterSubmit AfterSubmit { get; set; }
#endif
        /// <summary>Custom text that should be displayed alongside shipping address collection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextShippingAddress? ShippingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextShippingAddress ShippingAddress { get; set; }
#endif
        /// <summary>Custom text that should be displayed alongside the payment confirmation button.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextSubmit? Submit { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextSubmit Submit { get; set; }
#endif
        /// <summary>Custom text that should be displayed in place of the default terms of service agreement text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance? TermsOfServiceAcceptance { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance TermsOfServiceAcceptance { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomText"/> and sets the default values.
        /// </summary>
        public PaymentPagesCheckoutSessionCustomText()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomText"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomText CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomText();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "after_submit", n => { AfterSubmit = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextAfterSubmit>(global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextAfterSubmit.CreateFromDiscriminatorValue); } },
                { "shipping_address", n => { ShippingAddress = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextShippingAddress>(global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextShippingAddress.CreateFromDiscriminatorValue); } },
                { "submit", n => { Submit = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextSubmit>(global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextSubmit.CreateFromDiscriminatorValue); } },
                { "terms_of_service_acceptance", n => { TermsOfServiceAcceptance = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance>(global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextAfterSubmit>("after_submit", AfterSubmit);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextShippingAddress>("shipping_address", ShippingAddress);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextSubmit>("submit", Submit);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance>("terms_of_service_acceptance", TermsOfServiceAcceptance);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
