// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>For authenticated transactions: Indicates how the issuing bank authenticated the customer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceThreeDSecureAuthenticationFlow
    {
        [EnumMember(Value = "challenge")]
        #pragma warning disable CS1591
        Challenge,
        #pragma warning restore CS1591
        [EnumMember(Value = "frictionless")]
        #pragma warning disable CS1591
        Frictionless,
        #pragma warning restore CS1591
    }
}
