// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostThreeDSecureAuthenticationsXWwwFormUrlencodedRequestChannelThreeRiType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "delayed_shipment")]
        #pragma warning disable CS1591
        DelayedShipment,
        #pragma warning restore CS1591
        [EnumMember(Value = "other_payment")]
        #pragma warning disable CS1591
        OtherPayment,
        #pragma warning restore CS1591
        [EnumMember(Value = "recurring")]
        #pragma warning disable CS1591
        Recurring,
        #pragma warning restore CS1591
        [EnumMember(Value = "split_shipment")]
        #pragma warning disable CS1591
        SplitShipment,
        #pragma warning restore CS1591
    }
}
