// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostCheckoutSessions_branding_settings_border_style
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pill")]
        #pragma warning disable CS1591
        Pill,
        #pragma warning restore CS1591
        [EnumMember(Value = "rectangular")]
        #pragma warning disable CS1591
        Rectangular,
        #pragma warning restore CS1591
        [EnumMember(Value = "rounded")]
        #pragma warning disable CS1591
        Rounded,
        #pragma warning restore CS1591
    }
}
