// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>Controls how Stripe handles payment when a subscription update requires payment and `collection_method=charge_automatically`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostSubscriptionsSubscriptionExposedIdXWwwFormUrlencodedRequestPaymentBehavior
    {
        [EnumMember(Value = "allow_incomplete")]
        #pragma warning disable CS1591
        AllowIncomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "default_incomplete")]
        #pragma warning disable CS1591
        DefaultIncomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "error_if_incomplete")]
        #pragma warning disable CS1591
        ErrorIfIncomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_if_incomplete")]
        #pragma warning disable CS1591
        PendingIfIncomplete,
        #pragma warning restore CS1591
    }
}
