// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Cart details to display on the reader screen, including line items, amounts, and currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequestCart? Cart { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequestCart Cart { get; set; }
#endif
        /// <summary>Specifies which fields in the response should be expanded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Expand { get; set; }
#nullable restore
#else
        public List<string> Expand { get; set; }
#endif
        /// <summary>Type of information to be displayed by the reader. Only `cart` is currently supported.</summary>
        public global::Soenneker.Stripe.OpenApiClient.Models.CartType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cart", n => { Cart = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequestCart>(global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequestCart.CreateFromDiscriminatorValue); } },
                { "expand", n => { Expand = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.CartType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PostTerminalReadersReaderSetReaderDisplayXWwwFormUrlencodedRequestCart>("cart", Cart);
            writer.WriteCollectionOfPrimitiveValues<string>("expand", Expand);
            writer.WriteEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.CartType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
