// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostInvoicesCreatePreviewXWwwFormUrlencodedRequestSubscriptionDetailsBillingSchedulesAnyOf1ItemBillUntilType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "duration")]
        #pragma warning disable CS1591
        Duration,
        #pragma warning restore CS1591
        [EnumMember(Value = "timestamp")]
        #pragma warning disable CS1591
        Timestamp,
        #pragma warning restore CS1591
    }
}
