// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress"/>, <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddress : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress? PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2? PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2 PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddress();
            result.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress = new global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress();
            result.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2 = new global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress != null || PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress, PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress>(null, PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBillingDetailsAddress, PostPaymentIntentsIntentXWwwFormUrlencodedRequestPaymentMethodDataBillingDetailsAddressBranch2);
        }
    }
}
#pragma warning restore CS0618
