// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>
    /// Indicates the final outcome for the payment evaluation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RadarPaymentEvaluationOutcome : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details of a merchant_blocked outcome attached to this payment evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationMerchantBlocked? MerchantBlocked { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationMerchantBlocked MerchantBlocked { get; set; }
#endif
        /// <summary>The PaymentIntent ID associated with the payment evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentIntentId { get; set; }
#nullable restore
#else
        public string PaymentIntentId { get; set; }
#endif
        /// <summary>Details of an rejected outcome attached to this payment evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationRejected? Rejected { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationRejected Rejected { get; set; }
#endif
        /// <summary>Details of a succeeded outcome attached to this payment evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationSucceeded? Succeeded { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationSucceeded Succeeded { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.Models.RadarPaymentEvaluationOutcome"/> and sets the default values.
        /// </summary>
        public RadarPaymentEvaluationOutcome()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.RadarPaymentEvaluationOutcome"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.RadarPaymentEvaluationOutcome CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.RadarPaymentEvaluationOutcome();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "merchant_blocked", n => { MerchantBlocked = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationMerchantBlocked>(global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationMerchantBlocked.CreateFromDiscriminatorValue); } },
                { "payment_intent_id", n => { PaymentIntentId = n.GetStringValue(); } },
                { "rejected", n => { Rejected = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationRejected>(global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationRejected.CreateFromDiscriminatorValue); } },
                { "succeeded", n => { Succeeded = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationSucceeded>(global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationSucceeded.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationMerchantBlocked>("merchant_blocked", MerchantBlocked);
            writer.WriteStringValue("payment_intent_id", PaymentIntentId);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationRejected>("rejected", Rejected);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.InsightsResourcesPaymentEvaluationSucceeded>("succeeded", Succeeded);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
