// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>Select how to calculate the start of the invoice item period.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType
    {
        [EnumMember(Value = "max_item_period_start")]
        #pragma warning disable CS1591
        MaxItemPeriodStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "phase_start")]
        #pragma warning disable CS1591
        PhaseStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "timestamp")]
        #pragma warning disable CS1591
        Timestamp,
        #pragma warning restore CS1591
    }
}
