// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>When transitioning phases, controls how prorations are handled (if any). Possible values are `create_prorations`, `none`, and `always_invoice`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionSchedulePhaseConfigurationProrationBehavior
    {
        [EnumMember(Value = "always_invoice")]
        #pragma warning disable CS1591
        AlwaysInvoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_prorations")]
        #pragma warning disable CS1591
        CreateProrations,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
