// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>
    /// The most recent action performed by the reader.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TerminalReaderAction : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The reader action failed due to an [API error](https://docs.stripe.com/api/errors). Only present when `status` is `failed` and the underlying failure was an API error. Avoid parsing the `message` field for programmatic logic; use `type` or `code` instead. The `message` field is for display to humans only and may be updated at anytime. Requires [reader version](https://docs.stripe.com/terminal/readers/stripe-reader-s700-s710#reader-software-version) 2.42 or later. Readers on older versions always return null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionApiError? ApiError { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionApiError ApiError { get; set; }
#endif
        /// <summary>Represents a reader action to collect customer inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectInputsAction? CollectInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectInputsAction CollectInputs { get; set; }
#endif
        /// <summary>Represents a reader action to collect a payment method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectPaymentMethodAction? CollectPaymentMethod { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectPaymentMethodAction CollectPaymentMethod { get; set; }
#endif
        /// <summary>Represents a reader action to confirm a payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceConfirmPaymentIntentAction? ConfirmPaymentIntent { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceConfirmPaymentIntentAction ConfirmPaymentIntent { get; set; }
#endif
        /// <summary>Failure code, only set if status is `failed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureCode { get; set; }
#nullable restore
#else
        public string FailureCode { get; set; }
#endif
        /// <summary>Detailed failure message, only set if status is `failed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureMessage { get; set; }
#nullable restore
#else
        public string FailureMessage { get; set; }
#endif
        /// <summary>Represents a reader action to print content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourcePrintContent? PrintContent { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourcePrintContent PrintContent { get; set; }
#endif
        /// <summary>Represents a reader action to process a payment intent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessPaymentIntentAction? ProcessPaymentIntent { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessPaymentIntentAction ProcessPaymentIntent { get; set; }
#endif
        /// <summary>Represents a reader action to process a setup intent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessSetupIntentAction? ProcessSetupIntent { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessSetupIntentAction ProcessSetupIntent { get; set; }
#endif
        /// <summary>Represents a reader action to refund a payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceRefundPaymentAction? RefundPayment { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceRefundPaymentAction RefundPayment { get; set; }
#endif
        /// <summary>Represents a reader action to set the reader display</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceSetReaderDisplayAction? SetReaderDisplay { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceSetReaderDisplayAction SetReaderDisplay { get; set; }
#endif
        /// <summary>Status of the action performed by the reader.</summary>
        public global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionStatus? Status { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderAction"/> and sets the default values.
        /// </summary>
        public TerminalReaderAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_error", n => { ApiError = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionApiError>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionApiError.CreateFromDiscriminatorValue); } },
                { "collect_inputs", n => { CollectInputs = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectInputsAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectInputsAction.CreateFromDiscriminatorValue); } },
                { "collect_payment_method", n => { CollectPaymentMethod = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectPaymentMethodAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectPaymentMethodAction.CreateFromDiscriminatorValue); } },
                { "confirm_payment_intent", n => { ConfirmPaymentIntent = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceConfirmPaymentIntentAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceConfirmPaymentIntentAction.CreateFromDiscriminatorValue); } },
                { "failure_code", n => { FailureCode = n.GetStringValue(); } },
                { "failure_message", n => { FailureMessage = n.GetStringValue(); } },
                { "print_content", n => { PrintContent = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourcePrintContent>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourcePrintContent.CreateFromDiscriminatorValue); } },
                { "process_payment_intent", n => { ProcessPaymentIntent = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessPaymentIntentAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessPaymentIntentAction.CreateFromDiscriminatorValue); } },
                { "process_setup_intent", n => { ProcessSetupIntent = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessSetupIntentAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessSetupIntentAction.CreateFromDiscriminatorValue); } },
                { "refund_payment", n => { RefundPayment = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceRefundPaymentAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceRefundPaymentAction.CreateFromDiscriminatorValue); } },
                { "set_reader_display", n => { SetReaderDisplay = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceSetReaderDisplayAction>(global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceSetReaderDisplayAction.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionStatus>(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionApiError>("api_error", ApiError);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectInputsAction>("collect_inputs", CollectInputs);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceCollectPaymentMethodAction>("collect_payment_method", CollectPaymentMethod);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceConfirmPaymentIntentAction>("confirm_payment_intent", ConfirmPaymentIntent);
            writer.WriteStringValue("failure_code", FailureCode);
            writer.WriteStringValue("failure_message", FailureMessage);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourcePrintContent>("print_content", PrintContent);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessPaymentIntentAction>("process_payment_intent", ProcessPaymentIntent);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceProcessSetupIntentAction>("process_setup_intent", ProcessSetupIntent);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceRefundPaymentAction>("refund_payment", RefundPayment);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceSetReaderDisplayAction>("set_reader_display", SetReaderDisplay);
            writer.WriteEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.TerminalReaderReaderResourceReaderActionStatus>("status", Status);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
