// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>The type of link being generated.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TerminalOnboardingLinkLinkType
    {
        [EnumMember(Value = "apple_terms_and_conditions")]
        #pragma warning disable CS1591
        AppleTermsAndConditions,
        #pragma warning restore CS1591
    }
}
