// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.V1.Payment_intents.Item.Confirm
{
    /// <summary>Controls when the funds will be captured from the customer&apos;s account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfirmPostRequestBody_capture_method
    {
        [EnumMember(Value = "automatic")]
        #pragma warning disable CS1591
        Automatic,
        #pragma warning restore CS1591
        [EnumMember(Value = "automatic_async")]
        #pragma warning disable CS1591
        Automatic_async,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
