// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models.Identity
{
    /// <summary>Type of report.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Verification_report_type
    {
        [EnumMember(Value = "document")]
        #pragma warning disable CS1591
        Document,
        #pragma warning restore CS1591
        [EnumMember(Value = "id_number")]
        #pragma warning disable CS1591
        Id_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification_flow")]
        #pragma warning disable CS1591
        Verification_flow,
        #pragma warning restore CS1591
    }
}
