// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.V1.Checkout.Sessions
{
    /// <summary>Configure whether a Checkout Session creates a [Customer](https://stripe.com/docs/api/customers) during Session confirmation.When a Customer is not created, you can still retrieve email, address, and other customer data entered in Checkoutwith [customer_details](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-customer_details).Sessions that don&apos;t create Customers instead are grouped by [guest customers](https://stripe.com/docs/payments/checkout/guest-customers)in the Dashboard. Promotion codes limited to first time customers will return invalid for these Sessions.Can only be set in `payment` and `setup` mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionsPostRequestBody_customer_creation
    {
        [EnumMember(Value = "always")]
        #pragma warning disable CS1591
        Always,
        #pragma warning restore CS1591
        [EnumMember(Value = "if_required")]
        #pragma warning disable CS1591
        If_required,
        #pragma warning restore CS1591
    }
}
