// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models.Checkout
{
    /// <summary>Describes whether Checkout should collect the customer&apos;s billing address. Defaults to `auto`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Session_billing_address_collection
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
    }
}
