// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models.Treasury
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Outbound_payment_object
    {
        [EnumMember(Value = "treasury.outbound_payment")]
        #pragma warning disable CS1591
        TreasuryOutbound_payment,
        #pragma warning restore CS1591
    }
}
