// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Activate;
using Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Deactivate;
using Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Reject;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\test_helpers\issuing\personalization_designs\{personalization_design}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPersonalization_designItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activate property</summary>
        public global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Activate.ActivateRequestBuilder Activate
        {
            get => new global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deactivate property</summary>
        public global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Deactivate.DeactivateRequestBuilder Deactivate
        {
            get => new global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Deactivate.DeactivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reject property</summary>
        public global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Reject.RejectRequestBuilder Reject
        {
            get => new global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.Reject.RejectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.WithPersonalization_designItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPersonalization_designItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/test_helpers/issuing/personalization_designs/{personalization_design}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.V1.Test_helpers.Issuing.Personalization_designs.Item.WithPersonalization_designItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPersonalization_designItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/test_helpers/issuing/personalization_designs/{personalization_design}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
