// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models.Tax
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Transaction_object
    {
        [EnumMember(Value = "tax.transaction")]
        #pragma warning disable CS1591
        TaxTransaction,
        #pragma warning restore CS1591
    }
}
