// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.V1.Payouts
{
    /// <summary>The balance type of your Stripe balance to draw this payout from. Balances for different payment sources are kept separately. You can find the amounts with the Balances API. One of `bank_account`, `card`, or `fpx`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PayoutsPostRequestBody_source_type
    {
        [EnumMember(Value = "bank_account")]
        #pragma warning disable CS1591
        Bank_account,
        #pragma warning restore CS1591
        [EnumMember(Value = "card")]
        #pragma warning disable CS1591
        Card,
        #pragma warning restore CS1591
        [EnumMember(Value = "fpx")]
        #pragma warning disable CS1591
        Fpx,
        #pragma warning restore CS1591
    }
}
