// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.V1.Treasury.Transactions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrder_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "posted_at")]
        #pragma warning disable CS1591
        Posted_at,
        #pragma warning restore CS1591
    }
}
