// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Credit_note_object
    {
        [EnumMember(Value = "credit_note")]
        #pragma warning disable CS1591
        Credit_note,
        #pragma warning restore CS1591
    }
}
