// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>Type of installment plan, one of `fixed_count`, `bonus`, or `revolving`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Payment_method_details_card_installments_plan_type
    {
        [EnumMember(Value = "bonus")]
        #pragma warning disable CS1591
        Bonus,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed_count")]
        #pragma warning disable CS1591
        Fixed_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "revolving")]
        #pragma warning disable CS1591
        Revolving,
        #pragma warning restore CS1591
    }
}
