// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Portal_subscription_update : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The types of subscription updates that are supported for items listed in the `products` attribute. When empty, subscriptions are not updateable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_default_allowed_updates?>? DefaultAllowedUpdates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_default_allowed_updates?> DefaultAllowedUpdates { get; set; }
#endif
        /// <summary>Whether the feature is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The list of up to 10 products that support subscription updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_product>? Products { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_product> Products { get; set; }
#endif
        /// <summary>Determines how to handle prorations resulting from subscription updates. Valid values are `none`, `create_prorations`, and `always_invoice`. Defaults to a value of `none` if you don&apos;t set it during creation.</summary>
        public global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_proration_behavior? ProrationBehavior { get; set; }
        /// <summary>The schedule_at_period_end property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stripe.OpenApiClient.Models.Portal_resource_schedule_update_at_period_end? ScheduleAtPeriodEnd { get; set; }
#nullable restore
#else
        public global::Soenneker.Stripe.OpenApiClient.Models.Portal_resource_schedule_update_at_period_end ScheduleAtPeriodEnd { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update"/> and sets the default values.
        /// </summary>
        public Portal_subscription_update()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_allowed_updates", n => { DefaultAllowedUpdates = n.GetCollectionOfEnumValues<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_default_allowed_updates>()?.AsList(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_product>(global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_product.CreateFromDiscriminatorValue)?.AsList(); } },
                { "proration_behavior", n => { ProrationBehavior = n.GetEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_proration_behavior>(); } },
                { "schedule_at_period_end", n => { ScheduleAtPeriodEnd = n.GetObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.Portal_resource_schedule_update_at_period_end>(global::Soenneker.Stripe.OpenApiClient.Models.Portal_resource_schedule_update_at_period_end.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_default_allowed_updates>("default_allowed_updates", DefaultAllowedUpdates);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_product>("products", Products);
            writer.WriteEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Portal_subscription_update_proration_behavior>("proration_behavior", ProrationBehavior);
            writer.WriteObjectValue<global::Soenneker.Stripe.OpenApiClient.Models.Portal_resource_schedule_update_at_period_end>("schedule_at_period_end", ScheduleAtPeriodEnd);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
