// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>Controls how prorations and invoices for subscriptions are calculated and orchestrated.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Subscriptions_resource_billing_mode_type
    {
        [EnumMember(Value = "classic")]
        #pragma warning disable CS1591
        Classic,
        #pragma warning restore CS1591
        [EnumMember(Value = "flexible")]
        #pragma warning disable CS1591
        Flexible,
        #pragma warning restore CS1591
    }
}
