// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>
    /// Information about an input&apos;s toggle
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Terminal_reader_reader_resource_toggle : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The toggle&apos;s default value</summary>
        public global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_default_value? DefaultValue { get; set; }
        /// <summary>The toggle&apos;s description text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The toggle&apos;s title text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The toggle&apos;s collected value</summary>
        public global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_value? Value { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle"/> and sets the default values.
        /// </summary>
        public Terminal_reader_reader_resource_toggle()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_value", n => { DefaultValue = n.GetEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_default_value>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "value", n => { Value = n.GetEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_value>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_default_value>("default_value", DefaultValue);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Stripe.OpenApiClient.Models.Terminal_reader_reader_resource_toggle_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
