// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models
{
    /// <summary>The version of 3D Secure that was used.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Three_d_secure_details_charge_version
    {
        [EnumMember(Value = "1.0.2")]
        #pragma warning disable CS1591
        OneZeroTwo,
        #pragma warning restore CS1591
        [EnumMember(Value = "2.1.0")]
        #pragma warning disable CS1591
        TwoOneZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "2.2.0")]
        #pragma warning disable CS1591
        TwoTwoZero,
        #pragma warning restore CS1591
    }
}
