// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stripe.OpenApiClient.Models.Climate
{
    /// <summary>The current status of this order.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Order_status
    {
        [EnumMember(Value = "awaiting_funds")]
        #pragma warning disable CS1591
        Awaiting_funds,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "confirmed")]
        #pragma warning disable CS1591
        Confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
    }
}
